<?php

namespace Database\Seeders;

use App\Models\Scholarship;
use Illuminate\Database\Seeder;

class ScholarshipSeeder extends Seeder
{
    public function run(): void
    {
        $scholarships = [
            [
                'name' => 'TAIWAN INTERNATIONAL GRADUATE PROGRAM',
                'country' => 'TAIWAN',
                'deadline' => '27 JANUARY, 2026',
                'description' => 'Graduate scholarship program for international students in Taiwan',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Undergraduate certification if applying for postgraduate programme',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'SCHWARZMAN SCHOLARSHIPS',
                'country' => 'CHINA',
                'deadline' => '20 SEPTEMBER, 2025',
                'description' => 'Prestigious scholarship program in China',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Recommendation letter',
                ],
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'GOVERNMENT OF SWEDEN SCHOLARSHIP',
                'country' => 'SWEDEN',
                'deadline' => '28 FEBRUARY, 2026',
                'description' => 'Swedish government scholarship for international students',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 3,
            ],
            [
                'name' => 'SABANCI UNIVERSITY GRADUATE SCHOLARSHIP',
                'country' => 'TURKEY',
                'deadline' => '30 MAY, 2026',
                'description' => 'Graduate scholarship at Sabanci University',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Admission letter from Sabanci University',
                ],
                'is_active' => true,
                'order' => 4,
            ],
            [
                'name' => 'UMS INTERNATIONAL PRIORITY SCHOLARSHIP',
                'country' => 'INDONESIA',
                'deadline' => '25 MAY, 2026',
                'description' => 'International priority scholarship in Indonesia',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 5,
            ],
            [
                'name' => 'ANSO SCHOLARSHIP',
                'country' => 'CHINA',
                'deadline' => '15 FEBRUARY, 2026',
                'description' => 'ANSO scholarship program in China',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 6,
            ],
            [
                'name' => 'KAIST UNIVERSITY SCHOLARSHIP',
                'country' => 'KOREA',
                'deadline' => '28 DECEMBER, 2025',
                'description' => 'Scholarship at KAIST University in South Korea',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Admission letter from KAIST',
                ],
                'is_active' => true,
                'order' => 7,
            ],
            [
                'name' => 'NCTU SCHOLARSHIPS',
                'country' => 'CHINA',
                'deadline' => '30 SEPTEMBER, 2025',
                'description' => 'National Chiao Tung University scholarships',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 8,
            ],
            [
                'name' => 'GLOBAL KOREA SCHOLARSHIP',
                'country' => 'KOREA',
                'deadline' => 'VARIES',
                'description' => 'Global Korea scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 9,
            ],
            [
                'name' => 'FRIEDRICH EBERT FOUNDATION SCHOLARSHIP',
                'country' => 'GERMANY',
                'deadline' => '30 NOVEMBER, 2025',
                'description' => 'Friedrich Ebert Foundation scholarship in Germany',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Recommendation letter',
                ],
                'is_active' => true,
                'order' => 10,
            ],
            [
                'name' => 'CHULALONGKORN UNIVERSITY SCHOLARSHIPS',
                'country' => 'THAILAND',
                'deadline' => 'VARIES',
                'description' => 'Scholarships at Chulalongkorn University',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 11,
            ],
            [
                'name' => 'SINGA SCHOLARSHIP',
                'country' => 'SINGAPORE',
                'deadline' => '1 JUNE, 2026',
                'description' => 'Singapore scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 12,
            ],
            [
                'name' => 'BRITISH COUNCIL STEM SCHOLARSHIPS',
                'country' => 'UK',
                'deadline' => '22 MAY, 2026',
                'description' => 'STEM scholarships through British Council',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Recommendation letter',
                ],
                'is_active' => true,
                'order' => 13,
            ],
            [
                'name' => 'SCOTLAND GOVERNMENT SCHOLARSHIP',
                'country' => 'SCOTLAND',
                'deadline' => '31 MAY, 2026',
                'description' => 'Scottish government scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 14,
            ],
            [
                'name' => 'EXCELSIOR SCHOLARSHIP',
                'country' => 'USA',
                'deadline' => '31 JULY, 2026',
                'description' => 'Excelsior scholarship program in USA',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 15,
            ],
            [
                'name' => 'UNIVERSITY OF MICHIGAN SCHOLARSHIP',
                'country' => 'USA',
                'deadline' => '1 NOVEMBER, 2025',
                'description' => 'Scholarship at University of Michigan',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Admission letter from University of Michigan',
                ],
                'is_active' => true,
                'order' => 16,
            ],
            [
                'name' => 'HAMAD BIN KHALIFA UNIVERSITY SCHOLARSHIP',
                'country' => 'QATAR',
                'deadline' => '1 FEBRUARY, 2026',
                'description' => 'Scholarship at Hamad Bin Khalifa University',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 17,
            ],
            [
                'name' => 'AIT SCHOLARSHIP',
                'country' => 'THAILAND',
                'deadline' => '28 FEBRUARY, 2026',
                'description' => 'Asian Institute of Technology scholarship',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 18,
            ],
            [
                'name' => 'SBW BERLIN SCHOLARSHIP',
                'country' => 'GERMANY',
                'deadline' => 'VARIES',
                'description' => 'SBW Berlin scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 19,
            ],
            [
                'name' => 'ALBION COLLEGE',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Albion College scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 20,
            ],
            [
                'name' => 'VANDERBILT UNIVERSITY',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Vanderbilt University scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Admission letter from Vanderbilt University',
                ],
                'is_active' => true,
                'order' => 21,
            ],
            [
                'name' => 'UNIVERSITY OF RICHMOND',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'University of Richmond scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 22,
            ],
            [
                'name' => 'UNIVERSITY OF EAST LONDON',
                'country' => 'UK',
                'deadline' => 'VARIES',
                'description' => 'University of East London scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 23,
            ],
            [
                'name' => 'STANFORD UNIVERSITY',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Stanford University scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Admission letter from Stanford University',
                ],
                'is_active' => true,
                'order' => 24,
            ],
            [
                'name' => 'UNIVERSITY OF PENNSYLVANIA',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'University of Pennsylvania scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                    'Admission letter from University of Pennsylvania',
                ],
                'is_active' => true,
                'order' => 25,
            ],
            [
                'name' => 'RICE UNIVERSITY',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Rice University scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 26,
            ],
            [
                'name' => 'NORTHWESTERN UNIVERSITY',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Northwestern University scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 27,
            ],
            [
                'name' => 'DAVIDSON COLLEGE',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Davidson College scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 28,
            ],
            [
                'name' => 'TUFTS UNIVERSITY',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Tufts University scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 29,
            ],
            [
                'name' => 'GRINNELL COLLEGE',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Grinnell College scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 30,
            ],
            [
                'name' => 'COLGATE UNIVERSITY',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Colgate University scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 31,
            ],
            [
                'name' => 'MIDDLEBURY COLLEGE',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Middlebury College scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 32,
            ],
            [
                'name' => 'CARLETON COLLEGE',
                'country' => 'USA',
                'deadline' => 'VARIES',
                'description' => 'Carleton College scholarship program',
                'requirements' => [
                    'Transcript from the school',
                    'Certificates of completion',
                    'Passport',
                    'English proficiency test scores',
                ],
                'is_active' => true,
                'order' => 33,
            ],
        ];

        foreach ($scholarships as $scholarship) {
            Scholarship::updateOrCreate(
                ['name' => $scholarship['name'], 'country' => $scholarship['country']],
                $scholarship
            );
        }
    }
}
